name: 部署到 GitHub 页面
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    name: 部署到 GitHub 页面
    runs-on: ubuntu-latest
    steps:
      - name: 签出存储库
        uses: actions/checkout@v3

      - name: 设置 Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: 安装依赖项
        run: yarn install --frozen-lockfile
      - name: 清理缓存
        run: yarn clear
      - name: 构建翻译文件
        run: yarn write-translations
      - name: 构建站点
        run: yarn build

      # 部署到 GitHub 页面的常用操作：
      # 文档: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: 部署到 GitHub 页面
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 构建输出以发布到 “gh-pages” 分支：
          publish_dir: ./build
