name: 构建站点流水线
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    name: 构建站点
    runs-on: ubuntu-latest
    steps:
      - name: 签出存储库
        uses: actions/checkout@v3

      - name: 设置 Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: 安装依赖项
        run: yarn install --frozen-lockfile
      - name: 构建站点
        run: yarn build

      # 部署到 GitHub 页面的常用操作：
      # 文档: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      #- name: 部署到 GitHub 页面
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    # Build output to publish to the `gh-pages` branch:
      #    publish_dir: ./build
      #    # The following lines assign commit authorship to the official
      #    # GH-Actions bot for deploys to `gh-pages` branch:
      #    # https://github.com/actions/checkout/issues/13#issuecomment-724415212
      #    # The GH actions bot is used by default if you didn't specify the two fields.
      #    # You can swap them out with your own user credentials.
      #    user_name: github-actions[bot]
      #    user_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: SSH 部署
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}  # 引用配置，SSH私钥
          ARGS: '-rlgoDzvc -i'  # rsync参数
          REMOTE_PORT: '22'  # SSH端口
          SOURCE: 'build'   # 要推送的文件夹，路径相对于代码仓库的根目录
          REMOTE_HOST: ${{ secrets.SSH_HOST }}  # 引用配置，服务器的host名（IP或者域名domain.com）
          REMOTE_USER: ${{ secrets.SSH_USERNAME }} # 引用配置，服务器登录名
          TARGET: ${{ secrets.REMOTE_TARGET }}  # 部署到目标文件夹
